name: "KidsLock Manager"
version: "1.4.5"
slug: "kidslock-manager"
description: "Stabiele v1.3.0 basis met Onbeperkt modus en Edit-fix"
url: "https://github.com/svdveer/kidslock-repository"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
full_access: true
ingress: true
ingress_port: 8000
panel_icon: mdi:lock-settings
schema:
  mqtt:
    host: str
    port: int
    username: str
    password: str